### ISSUE TITLE
Any Docs?

### ISSUE THREAD

**Issue by vitorlans** [CastleCSS/castlecss-core#6]
is there any documentation or website that uses CastleCSS?

**Comment by dariusrosendahl** [comment]
Good question, we're currently in the process of making the website and documentation. It won't be long any more ;)

**Comment by dariusrosendahl** [comment]
We just released the documentation! www.castlecss.com

Or you can download it in the [CastleCSS Full Package](https://github.com/CastleCSS/castlecss) / [CastleCSS Docs](https://github.com/CastleCSS/castlecss-docs)
