### ISSUE TITLE
Specific utility spacing classes do not overwrite general spacing classes

### ISSUE THREAD

**Issue by dariusrosendahl** [CastleCSS/castlecss-core#7]
Ideally you'll want that pt-2x (padding-top: 2x) overwrites p-3x (padding: 3x) because it's more specific.

![](https://cloud.githubusercontent.com/assets/7299359/17368174/394f13d0-5993-11e6-8c69-5430e6a2b1dd.png)

![](https://cloud.githubusercontent.com/assets/7299359/17368175/3950f042-5993-11e6-843c-dffd7b555dc6.png)

**Comment by Paulus90** [comment]
See pull request #26

**Comment by Paulus90** [comment]
Better solution would be to declare all longhands after the shorthands

**Comment by dariusrosendahl** [comment]
Merged with develop. Will be added in the next release.
